# Specify that this pipeline is on merge request only
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

include:
   - 'https://git.ovh.iot/redpesk/redpesk-devtools/gitlab-ci-factory-templates/-/raw/master/.rp-cli-template-ci.yml'

stages:
  - lint
  - test-py
  - build_factory
  - redtest_factory

default:
  tags:
    - redpesk-batz

lint:
  stage: lint
  script:
    - bash -x tests/ci/lint.sh
  allow_failure: true

test-py:
  stage: test-py
  script:
    - bash -x tests/ci/test_and_coverage.sh
  artifacts:
    paths:
      - html/
      - coverage.xml
    expose_as: 'Coverage report'
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: '/Total:\|(\d+\.?\d+\%)/'

build_factory:
  stage: build_factory
  extends: .rp-cli-build

redtest_factory:
  stage: redtest_factory
  needs:
    - build_factory
  extends: .rp-cli-test
  
