# This file is part of the RedPesK project.
include:
   - 'https://raw.githubusercontent.com/redpesk-devtools/gitlab-ci-factory-templates/refs/heads/master/.rp-cli-template-ci.yml'

stages:
  - lint
  - build_factory
  - redtest_factory

default:
  tags:
    - redpesk-batz

lint:
  stage: lint
  script:
    - bash -x tests/ci/lint.sh
  allow_failure: true

build_factory:
  stage: build_factory
  extends:
    - .rp-cli-install 
    - .rp-cli-build

redtest_factory:
  stage: redtest_factory
  needs:
    - build_factory
  extends:
    - .rp-cli-install
    - .rp-cli-start-test
