# Specify that this pipeline is on merge request only
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - lint
  - test-py
  - build-factory
  - redtest-factory

default:
  tags:
    - redpesk-batz

lint:
  stage: lint
  needs: []
  script:
    - bash -x tests/ci/lint.sh
  allow_failure: true

test-py:
  stage: test-py
  needs: []
  script:
    - bash -x tests/ci/test_and_coverage.sh
  artifacts:
    paths:
      - html/
      - coverage.xml
    expose_as: 'Coverage report'
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: '/Total:\|(\d+\.?\d+\%)/'

build-factory:
  stage: build-factory
  needs: []
  script:
    - bash -x tests/build_fact.sh "$RP_REMOTE_FACTORY_NAME" "$RP_REMOTE_FACTORY_TOKEN" "$RP_REMOTE_FACTORY_URL" "$RP_REMOTE_FACTORY_PROJECT" "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"

redtest-factory:
  stage: redtest-factory
  needs:
    - job: build-factory
  script:
    - bash -x tests/redtest_fact.sh "$RP_REMOTE_FACTORY_PROJECT"
  allow_failure: false
